### ISSUE TITLE
Including pytest-faker into Faker

### ISSUE THREAD

**Issue by fcurella** [pytest-dev/pytest-faker#11]
Hi,

I’m the maintainer of https://github.com/joke2k/faker. 

I think it would make sense to include this plugin right into Faker. Users will have one less package to install, and the pytest-dev team will have one less package to maintain. I can submit the PR myself, and have you review it.

Let me know if you’re interested :)

**Comment by cognifloyd** [comment]
I think including pytest-faker in Faker makes a lot of sense. That simplifies the dependency list and might make it more natural to add pytest fixtures for more of faker's features.

**Comment by bubenkoff** [comment]
@fcurella 
makes total sense, no need to review by me, but maybe @cognifloyd will be interested to review

**Comment by RonnyPfannschmidt** [comment]
after the inteegration is complete, there perhaps should be a release of pytest-faker which is "empty" and informs people, so things sort themselfes out cleanly

**Comment by fcurella** [comment]
@cognifloyd I've got a PR up if you're interested: https://github.com/joke2k/faker/pull/1101

**Comment by fcurella** [comment]
heads up, I just merged the new pytest plugin into Faker. Let me know if we need to coordinate releases somehow. As a general rule, I release around the 12th of each month (unless it's weekend), but I"m pretty flexible.

**Comment by fcurella** [comment]
Just wanted to let you know I've released Faker v4.1.0, which includes the plugin.

**Comment by bubenkoff** [comment]
@fcurella should we then just remove this repo?

**Comment by fcurella** [comment]
@bubenkoff I think you could just archive it

**Comment by bubenkoff** [comment]
@fcurella added a note about deprecation in the readme
