### ISSUE TITLE
ImportError: The ``fake-factory`` package is now called ``Faker``

### ISSUE THREAD

**Issue by robkorv** [pytest-dev/pytest-faker#4]
Faker just released 0.7.5 which breaks this package.

A quickfix is to pin ~~`faker==0.7.3`~~ `fake-factory==0.7.4` before installing `pytest-faker`.

**Comment by robkorv** [comment]
I just noticed there is a failing pull request for this. See: https://github.com/pytest-dev/pytest-faker/pull/3

**Comment by robkorv** [comment]
The quickfix I mentioned above doesn't work. `faker` should by uninstalled. `fake-factory==0.7.4` works.

**Comment by bubenkoff** [comment]
can you maybe submit a PR fixing the support of the recent faker?

**Comment by bubenkoff** [comment]
ok, did it myself :)
2.0.0 is out
