### ISSUE TITLE
Repo missing LICENSE

### ISSUE THREAD

**Issue by smarlowucf** [pytest-dev/pytest-faker#5]
I am attempting to package this project. However, there is no copy of the MIT LICENSE in the repo. Can a LICENSE file be added and included in the MANIFEST so it is added to tarball?

**Comment by RonnyPfannschmidt** [comment]
if you open a pr with that i'd be delighted to press the merge button

**Comment by smarlowucf** [comment]
I'm happy to provide a PR but I only can guess at who the copyright should attribute:

`Anatoly Bubenkov, Oleg Pidsadnyi and others`?

**Comment by RonnyPfannschmidt** [comment]
it does seem that way, wrt that one im just going to follow your guess, i have no idea
