### ISSUE TITLE
Tests are not included in manifest

### ISSUE THREAD

**Issue by smarlowucf** [pytest-dev/pytest-faker#6]
Add tests dir to manifest so they are included in tarball.

**Comment by bubenkoff** [comment]
@smarlowucf and why are those needed in the tarball?

**Comment by RonnyPfannschmidt** [comment]
@bubenkoff thats a typical use-case/need for downstream packaging

**Comment by smarlowucf** [comment]
Yep, main use case is for downstream packaging.
